services:
  mealie:
    image: hkotel/mealie
    container_name: mealie
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres:postgres
    labels:
      - traefik.http.routers.mealie.rule=Host(`food.gpzeke.com`)
      - traefik.http.routers.mealie.entrypoints=websecure
      - traefik.enable=true
      - traefik.http.routers.mealie.tls.certresolver=certificate
      - traefik.http.routers.mealie.tls.domains[0].main=food.gpzeke.com
    environment:
      TZ: America/Chicago
      DEFAULT_USER: ${DEFAULT_USER}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      DB_ENGINE: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      WEB_CONCURRENCY: 2
    volumes:
      - ../container/mealie/data/:/app/data
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mealie
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Chicago
    volumes:
      - ../container/postgres/:/var/lib/postgresql/data

networks:
  default:
    external: "true"
    name: traefik_default